config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create, :update] do
    member do
      get 'myarts', to: 'myarts'
    end
  end
  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :articles, only: [:index, :show]
  
  get 'books', to: 'books#index'
  
  resources :user_art_connects, only: [:create, :destroy]
  resources :memos, only: [:create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  default_scope -> { order(date: :desc) }
  has_many :user_art_connect
  has_many :user, through: :user_art_connect
  has_many :memos
  has_many :memo_users, through: :users, class_name: 'User', source: :user
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/favorite.rb
class Favorite < UserArtConnect
end

app/models/memo.rb
class Memo < UserArtConnect
end

app/models/readlater.rb
class Readlater < UserArtConnect
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :user_art_connect
  has_many :article, through: :user_art_connect
  has_many :favorites
  has_many :favorite_items, through: :favorites, class_name: 'Article', source: :article
  has_many :readlaters
  has_many :readlater_items, through: :readlaters, class_name: 'Article', source: :article
  has_many :memos
  has_many :memo_items, through: :memos, class_name: 'Memo', source: :memo
  
  def favorite(article)
    self.favorites.find_or_create_by(article_id: article.id)
  end
  
  def unfavorite(article)
    fav = self.favorites.find_by(article_id: article.id)
    fav.destroy if fav
  end
  
  def favorite?(article)
    self.favorite_items.include?(article)
  end
  
  def readlater(article)
    self.readlaters.find_or_create_by(article_id: article.id)
  end
  
  def unreadlater(article)
    lat = self.readlaters.find_by(article_id: article.id)
    lat.destroy if lat
  end
  
  def readlater?(article)
    self.readlater_items.include?(article)
  end
end

app/models/user_art_connect.rb
class UserArtConnect < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  @all = Article.all
  @qiita = Article.where(site_name: 'Qiita')
  @gn = Article.where(site_name: 'GoogleNews')
  end
  
  def show
  @article = Article.find_by(id: params['id'])
  @memo = @article.memos.find_or_create_by(user_id: current_user.id)
  end
end
# https://qiita.com/dawn_628/items/13fa64dc6d600e921ce3

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def create
    @memo = Memo.new(memo_params)
    @memo.save
    Article.update(params['memo']['article_id'], {is_hold: true})
    redirect_back(fallback_location: root_path)
  end

  def update
    @memo = Memo.find(params[:id])
    @memo.update(memo_params)
    Article.update(params['memo']['article_id'], {is_hold: true})
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def memo_params
    params.require(:memo).permit(:type, :content, :user_id, :article_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index

  end
end

app/controllers/user_art_connects_controller.rb
class UserArtConnectsController < ApplicationController
  def create
    puts params
    @article = Article.find_by(id: params[:article_id])
    
    if params[:type] == 'Favorite'
      current_user.favorite(@article)
      Article.update(@article.id, {is_hold: true})
    elsif params[:type] == 'Readlater'
      current_user.readlater(@article)
      Article.update(@article.id, {is_hold: true})
    end

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @article = Article.find_by(id: params[:article_id])

    if params[:type] == 'Favorite'
      current_user.unfavorite(@article)
      Article.update(@article.id, {is_hold: false})
    elsif params[:type] == 'Readlater'
      current_user.unreadlater(@article)
      Article.update(@article.id, {is_hold: false})
    end


    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :myart, :update]
  before_action :correct_user, only: [:show, :myart]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to @user
    else
      render :show
    end
  end
  
  def myarts
    @favorites = current_user.favorite_items
    @readlaters = current_user.readlater_items
  end
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def correct_user
    if current_user.id != params[:id].to_i
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/
#{gravatar_id}
?s=
#{size}
&d=mm"
  end
end

app/views/articles/_articles.html.erb
  <% articles.each do |article| %>
    <div class="articles">
      <div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row article">
              <div class="col-xs-2", id='article_col'>
            <img src= <%= article['image_url'] %> >
              </div>
              <div class="col-xs-10">
                <p class="article-title">
                  <a href="<%= article['url'] %>" target="_blank"><%= article["title"] %></a>
                </p>
                <p> <%= article['date'] %> </p>
              </div>
            </div>
            <div class='row bottuns'>
              <div class='col-xs-4'>
                <%= render '/user_art_connects/readlater_button', article: article %>
              </div>
              <div class='col-xs-4'>
                <%= render '/user_art_connects/favorite_button', article: article %>
              </div>
              <div class='col-xs-4'>
                <%= link_to 'Memo', article_path(article), class: "btn btn-primary"%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
    <ul class='nav nav-tabs'>
        <li class='nav-item'>
            <a href="#All" class="nav-link" data-toggle="tab">All</a>
        </li>
        <li class='nav-item'>
            <a href="#Qiita" class="nav-link" data-toggle="tab">Qiita</a>
        </li>
        <li class='nav-item'>
            <a href="#GoogleNews" class="nav-link" data-toggle="tab">Google News</a>
        </li>
    </ul>
    <div class='tab-content'>
        <div id='All' class='tab-pane active'>
            <%= render "articles", articles: @all %>
        </div>
        <div id='Qiita' class='tab-pane'>
            <%= render "articles", articles: @qiita %>
        </div>
        <div id='GoogleNews' class='tab-pane'>
            <%= render "articles", articles: @gn %>
        </div>
    </div>
    
  </div>
</div>

app/views/articles/show.html.erb
<div class='row article_memo'>
  <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
    <%= render "articles", articles: [@article] %>
  </div>
  
  <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 article_memo_in">
    <%= form_for(@memo, html: {class: 'article_memo_in'} ) do |f| %>
    <%= f.hidden_field :article_id, :value => params['id'] %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :type, :value => 'Memo' %>
    <div class='form-group article_memo_in'>
      <%= f.label :content, 'メモ' %>
      <%= f.text_area :content , class: 'form-control', id: 'memo_field'%>
    </div>
    <%= f.submit "投稿", class: 'form-control btn btn-info'%>
    <% end %>
  </div>
</div>

app/views/books/_books.html.erb
  <div class="books">
    <% books.each do |book| %>
      <div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row book">
              <div class="col-xs-4">
            <img src="<%= book['image_url'] %>" >
              </div>
              <div class="col-xs-8">
            <p class="book-title">
              <a href="<%= book["url"] %>" target="_blank"><%= book["title"] %></a>
            </p>
            <p>発売日: <%= book['salesdate'] %> 価格: <%= book['itemprice'] %>円 </p>
            </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/books/index.html.erb
<div class="row">
     <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
    <%= render "books", books: @books %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% if logged_in? %>
          <%= link_to 'ML Media', myarts_user_path(current_user), class: 'navbar-brand'%>
        <% else %>
          <a class="navbar-brand" href="/">ML Media</a>
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'News', articles_path %></li>
            <li><%= link_to 'Books', books_path %></li>
            <li class='dropdown'>
              <a href='#' class='dropdown-toggle' data-toggle='dropdown' role="button" aria-haspopup="true" aria-expanded="false">
                <span class='gravatar'>
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
                </span>
                <%= current_user.name %>
                <span class='caret'></span>
              </a>
              <ul class='dropdown-menu'>
                <li>
                  <%= link_to 'My page', user_path(current_user) %>
                </li>
                <li>
                  <%= link_to '保存した記事', myarts_user_path(current_user) %>
                </li>
                <li role='separator' class='divider'></li>
                <li>
                  <%= link_to 'Logout', logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Sign up', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ML media</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield :cover %>

    <div class='container'>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/memos/create.html.erb
<h1>Memos#create</h1>
<p>Find me in app/views/memos/create.html.erb</p>

app/views/memos/destroy.html.erb
<h1>Memos#destroy</h1>
<p>Find me in app/views/memos/destroy.html.erb</p>

app/views/memos/update.html.erb
<h1>Memos#update</h1>
<p>Find me in app/views/memos/update.html.erb</p>

app/views/toppages/index.html.erb
<% content_for :cover do %>
<div class='center jumbotron'>
  <div class='text-center'>
    <h1>ようこそ</h1>
    <p>ML Mediaは、機械学習関連のニュースや書籍情報をまとめたサイトです</p>
    
    <%= link_to 'Sign up!', signup_path , class: 'btn btn-success btn-lg'%>
    <%= link_to 'Login!', login_path , class: 'btn btn-success btn-lg'%>
  </div>
</div>
<% end %>

app/views/user_art_connects/_favorite_button.html.erb
<% if current_user.favorite?(article) %>
  <%= form_tag(user_art_connect_path(article.id), method: :delete) do %>
    <%= hidden_field_tag :article_id, article.id %>
    <%= hidden_field_tag :type, 'Favorite' %>
    <%= submit_tag 'Favorite', class: 'btn btn-success' %>
  <% end %>
<% else %>
  <%= form_tag(user_art_connects_path, class: 'form-inline') do %>
    <%= hidden_field_tag :article_id, article.id %>
    <%= hidden_field_tag :type, 'Favorite' %>
    <%= submit_tag 'Favorite it', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/user_art_connects/_readlater_button.html.erb
<% if current_user.readlater?(article) %>
  <%= form_tag(user_art_connect_path(article.id), method: :delete) do %>
    <%= hidden_field_tag :article_id, article.id %>
    <%= hidden_field_tag :type, 'Readlater' %>
    <%= submit_tag 'あとで読む 済み', class: 'btn btn-success' %>
  <% end %>
<% else %>
  <%= form_tag(user_art_connects_path) do %>
    <%= hidden_field_tag :article_id, article.id %>
    <%= hidden_field_tag :type, 'Readlater' %>
    <%= submit_tag 'あとで読む', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/users/myarts.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
    <ul class='nav nav-tabs'>
        <li class='nav-item'>
            <a href="#Readlater" class="nav-link" data-toggle="tab">あとで読む</a>
        </li>
        <li class='nav-item'>
            <a href="#Favorite" class="nav-link" data-toggle="tab">Favorite</a>
        </li>
    </ul>
    <div class='tab-content'>
        <div id='Favorite' class='tab-pane '>
            <%= render "/articles/articles", articles: @favorites %>
        </div>
        <div id='Readlater' class='tab-pane active'>
            <%= render "/articles/articles", articles: @readlaters %>
        </div>
    </div>
    
  </div>
</div>

app/views/users/new.html.erb
<div class='row'>
  <div class= 'col-xs-offset-3 col-xs-6'>
    <div class='panel panel-default'>
      <div class='panel-heading'>会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <div class='form-group'>
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

            <%= f.submit '登録する', class: 'btn btn-success btn-block' %>
        <% end %>
    </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class='user-profile'>
<div class='row'>
  <div class= 'col-xs-offset-3 col-xs-6'>
    <div class='panel panel-default'>
      <div class='panel-heading'>登録情報</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <div class='form-group'>
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

            <%= f.submit '変更する', class: 'btn btn-success btn-block' %>
        <% end %>
    </div>
  </div>
</div>
</div>
</div>